// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7u0CMho7Cdwn4Kmgv811SdsG72Ql7qA',
    appId: '1:824657122472:web:e255d009a9a5d1c0261e9d',
    messagingSenderId: '824657122472',
    projectId: 'gameapp-69',
    authDomain: 'gameapp-69.firebaseapp.com',
    storageBucket: 'gameapp-69.appspot.com',
    measurementId: 'G-YDBWFXJ6FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJmLY1excdRjJa6QzLuyK3Pk-uO5z5m9k',
    appId: '1:824657122472:android:6c1b2203c8ebd9a3261e9d',
    messagingSenderId: '824657122472',
    projectId: 'gameapp-69',
    storageBucket: 'gameapp-69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo7Dvr6cGiLUncDpGSSUEcbNg1ujhOrfI',
    appId: '1:824657122472:ios:59b7e92125853cd1261e9d',
    messagingSenderId: '824657122472',
    projectId: 'gameapp-69',
    storageBucket: 'gameapp-69.appspot.com',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENqHbDu_0ONF2Swzha49cYL9QMR1ZsjM',
    appId: '1:642086517417:web:8767647b3c86b3344947b8',
    messagingSenderId: '642086517417',
    projectId: 'lati-games-69',
    authDomain: 'lati-games-69.firebaseapp.com',
    storageBucket: 'lati-games-69.appspot.com',
    measurementId: 'G-RWGVCQZ4QH',
  );

}